name: taxito
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: ^3.10.0


dependencies:
  flutter:
    sdk: flutter

  ### Common Package
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  flutter_cache_manager: ^3.4.1
  flutter_polyline_points: ^3.1.0
  permission_handler: ^12.0.1
  flutter_email_sender: ^8.0.0
  logger: ^2.6.2
  uuid: ^4.5.2
  change_app_package_name: any

  flutter_gen: ^5.12.0
  flutter_lazy_indexed_stack: ^0.0.6
  flutter_secure_storage: ^9.2.4
  chips_choice: ^3.0.1
  flutter_colorpicker: ^1.1.0
  timelines_plus: ^1.0.7
  collection: ^1.19.0
  flutter_animarker: ^3.4.0-beta.1
  force_update_helper:
  flutter_background_service: ^5.1.0
  easy_stepper: ^0.8.5+1
  app_settings: ^6.1.1
  readmore:

  ### Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  ### Firebase
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  firebase_crashlytics: ^5.0.2
  firebase_analytics: ^12.0.2
  flutter_animate: ^4.5.2



  ### Networking
  dio: ^5.7.0
  connectivity_plus: ^6.1.0
  url_launcher: ^6.3.1
  app_links: ^6.3.3
  socket_io_client: ^3.0.2
  loader_overlay: ^5.0.0

  ### Location
  location: ^8.0.0
  geocoding: ^4.0.0
  geolocator: ^13.0.4
  google_maps_flutter: ^2.12.1
  open_settings_plus: ^0.4.0


  ### Media
  flutter_blurhash: ^0.8.2
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  flutter_svg: ^2.0.10+1

  ### Ui Design
  another_flushbar: ^1.12.30
  cached_network_image: ^3.4.1
  fluttertoast: ^8.2.8
  loading_animation_widget: ^1.3.0
  carousel_slider: ^5.0.0
  animations: ^2.0.11
  smooth_page_indicator: ^1.2.0
  shimmer: ^3.0.0
  intl_phone_field:
    git:
      url: https://github.com/diaaossam/intl_phone_field.git
      ref: master
  pin_code_fields: ^8.0.1
  infinite_scroll_pagination: ^4.0.0
  share_plus: ^11.0.0
  modal_bottom_sheet: ^3.0.0
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.1.0
  flutter_screenutil: ^5.9.3
  photo_view: ^0.15.0

  ### State Management
  flutter_bloc: ^8.1.6

  ### clean architecture
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^8.0.2
  flutter_dotenv: ^5.2.1
  injectable: ^2.5.0
  page_transition: ^2.1.0
  like_button: ^2.0.5
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env.development

  fonts:
    - family: SomarSans
      fonts:
        - asset: assets/fonts/somar_sans/SomarSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/somar_sans/SomarSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/somar_sans/SomarSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/somar_sans/SomarSans-Regular.ttf
          weight: 400


flutter_intl:
  enabled: true

